### PR TITLE
feat: Add TypeScript 5 to peer dependencies

### PR DESCRIPTION
**Pull request by amannn**

### CODE REVIEW

**Comment by milesj** [comment]
Can you update the other deps to v5 too and make sure nothing breaks?

**Comment by milesj** [comment]
Good enough, I'll merge through. Thanks!

**Comment by amannn** [comment]
Thanks a lot for merging @milesj! Do you have plans for a release?

**Comment by milesj** [comment]
Thanks for the reminder, done.

**Pull request merged**
